module.exports = [{
  "Rank": "1",
  "Player Name": "McCoy, LeSean",
  "Team": "PHI",
  "Position": "RB",
  "Bye": "Wk 7",
  "Yards": "512",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "290",
  "Avg": "9.3",
  "Rec": "55",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "2",
  "Player Name": "Charles, Jamaal",
  "Team": "KC",
  "Position": "RB",
  "Bye": "Wk 6",
  "Yards": "566",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "249",
  "Avg": "8.6",
  "Rec": "66",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "3",
  "Player Name": "Peterson, Adrian",
  "Team": "MIN",
  "Position": "RB",
  "Bye": "Wk 10",
  "Yards": "188",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "294",
  "Avg": "7.5",
  "Rec": "25",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "4",
  "Player Name": "Forte, Matt",
  "Team": "CHI",
  "Position": "RB",
  "Bye": "Wk 9",
  "Yards": "488",
  "TD": "2",
  "INT": "0",
  "YPA": "0",
  "Att": "275",
  "Avg": "7.2",
  "Rec": "68",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "5",
  "Player Name": "Lacy, Eddie",
  "Team": "GB",
  "Position": "RB",
  "Bye": "Wk 9",
  "Yards": "311",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "296",
  "Avg": "6.9",
  "Rec": "45",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "6",
  "Player Name": "Johnson, Calvin",
  "Team": "DET",
  "Position": "WR",
  "Bye": "Wk 9",
  "Yards": "1501",
  "TD": "13",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "16",
  "Rec": "94",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "7",
  "Player Name": "Ball, Montee",
  "Team": "DEN",
  "Position": "RB",
  "Bye": "Wk 4",
  "Yards": "266",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "255",
  "Avg": "8.6",
  "Rec": "31",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "8",
  "Player Name": "Thomas, Demaryius",
  "Team": "DEN",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "1405",
  "TD": "13",
  "INT": "0",
  "YPA": "0",
  "Att": "2",
  "Avg": "15.4",
  "Rec": "91",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "9",
  "Player Name": "Graham, Jimmy",
  "Team": "NO",
  "Position": "TE",
  "Bye": "Wk 6",
  "Yards": "1123",
  "TD": "12",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "13.5",
  "Rec": "83",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "10",
  "Player Name": "Bryant, Dez",
  "Team": "DAL",
  "Position": "WR",
  "Bye": "Wk 11",
  "Yards": "1289",
  "TD": "13",
  "INT": "0",
  "YPA": "0",
  "Att": "2",
  "Avg": "14.3",
  "Rec": "90",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "11",
  "Player Name": "Murray, DeMarco",
  "Team": "DAL",
  "Position": "RB",
  "Bye": "Wk 11",
  "Yards": "312",
  "TD": "2",
  "INT": "0",
  "YPA": "0",
  "Att": "241",
  "Avg": "6.5",
  "Rec": "48",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "12",
  "Player Name": "Jones, Julio",
  "Team": "ATL",
  "Position": "WR",
  "Bye": "Wk 9",
  "Yards": "1389",
  "TD": "11",
  "INT": "0",
  "YPA": "0",
  "Att": "2",
  "Avg": "16",
  "Rec": "87",
  "Status": "Prob",
  "Injury Type": "Foot"
}, {
  "Rank": "13",
  "Player Name": "Green, A.J.",
  "Team": "CIN",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "1388",
  "TD": "11",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "15.3",
  "Rec": "91",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "14",
  "Player Name": "Morris, Alfred",
  "Team": "WAS",
  "Position": "RB",
  "Bye": "Wk 10",
  "Yards": "121",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "282",
  "Avg": "9.3",
  "Rec": "13",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "15",
  "Player Name": "Foster, Arian",
  "Team": "HOU",
  "Position": "RB",
  "Bye": "Wk 10",
  "Yards": "344",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "244",
  "Avg": "8.8",
  "Rec": "39",
  "Status": "Prob",
  "Injury Type": "Undisclosed"
}, {
  "Rank": "16",
  "Player Name": "Stacy, Zac",
  "Team": "STL",
  "Position": "RB",
  "Bye": "Wk 4",
  "Yards": "222",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "273",
  "Avg": "6.5",
  "Rec": "34",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "17",
  "Player Name": "Bernard, Giovani",
  "Team": "CIN",
  "Position": "RB",
  "Bye": "Wk 4",
  "Yards": "555",
  "TD": "2",
  "INT": "0",
  "YPA": "0",
  "Att": "212",
  "Avg": "9.3",
  "Rec": "60",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "18",
  "Player Name": "Bell, Le'Veon",
  "Team": "PIT",
  "Position": "RB",
  "Bye": "Wk 12",
  "Yards": "377",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "267",
  "Avg": "9.2",
  "Rec": "41",
  "Status": "Prob",
  "Injury Type": "Hamstring"
}, {
  "Rank": "19",
  "Player Name": "Lynch, Marshawn",
  "Team": "SEA",
  "Position": "RB",
  "Bye": "Wk 4",
  "Yards": "277",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "250",
  "Avg": "9.9",
  "Rec": "28",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "20",
  "Player Name": "Manning, Peyton",
  "Team": "DEN",
  "Position": "QB",
  "Bye": "Wk 4",
  "Yards": "0",
  "TD": "0",
  "INT": "14",
  "YPA": "7.8",
  "Att": "23",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "21",
  "Player Name": "Martin, Doug",
  "Team": "TB",
  "Position": "RB",
  "Bye": "Wk 7",
  "Yards": "255",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "250",
  "Avg": "8.8",
  "Rec": "29",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "22",
  "Player Name": "Spiller, C.J.",
  "Team": "BUF",
  "Position": "RB",
  "Bye": "Wk 9",
  "Yards": "344",
  "TD": "2",
  "INT": "0",
  "YPA": "0",
  "Att": "201",
  "Avg": "8.4",
  "Rec": "41",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "23",
  "Player Name": "Marshall, Brandon",
  "Team": "CHI",
  "Position": "WR",
  "Bye": "Wk 9",
  "Yards": "1211",
  "TD": "11",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "12.9",
  "Rec": "94",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "24",
  "Player Name": "Nelson, Jordy",
  "Team": "GB",
  "Position": "WR",
  "Bye": "Wk 9",
  "Yards": "1267",
  "TD": "10",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "15.1",
  "Rec": "84",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "25",
  "Player Name": "Jeffery, Alshon",
  "Team": "CHI",
  "Position": "WR",
  "Bye": "Wk 9",
  "Yards": "1255",
  "TD": "9",
  "INT": "0",
  "YPA": "0",
  "Att": "8",
  "Avg": "14.9",
  "Rec": "84",
  "Status": "Prob",
  "Injury Type": "Foot"
}, {
  "Rank": "26",
  "Player Name": "Ellington, Andre",
  "Team": "ARZ",
  "Position": "RB",
  "Bye": "Wk 4",
  "Yards": "455",
  "TD": "2",
  "INT": "0",
  "YPA": "0",
  "Att": "193",
  "Avg": "10.3",
  "Rec": "44",
  "Status": "Prob",
  "Injury Type": "Neck"
}, {
  "Rank": "27",
  "Player Name": "Allen, Keenan",
  "Team": "SD",
  "Position": "WR",
  "Bye": "Wk 10",
  "Yards": "1234",
  "TD": "10",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "14.2",
  "Rec": "87",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "28",
  "Player Name": "Rodgers, Aaron",
  "Team": "GB",
  "Position": "QB",
  "Bye": "Wk 9",
  "Yards": "0",
  "TD": "0",
  "INT": "10",
  "YPA": "8.2",
  "Att": "65",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "29",
  "Player Name": "Mathews, Ryan",
  "Team": "SD",
  "Position": "RB",
  "Bye": "Wk 10",
  "Yards": "213",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "244",
  "Avg": "6.9",
  "Rec": "31",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "30",
  "Player Name": "Gronkowski, Rob",
  "Team": "NE",
  "Position": "TE",
  "Bye": "Wk 10",
  "Yards": "908",
  "TD": "10",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "12.6",
  "Rec": "72",
  "Status": "Prob",
  "Injury Type": "Knee"
}, {
  "Rank": "31",
  "Player Name": "Sankey, Bishop",
  "Team": "TEN",
  "Position": "RB",
  "Bye": "Wk 9",
  "Yards": "287",
  "TD": "2",
  "INT": "0",
  "YPA": "0",
  "Att": "222",
  "Avg": "9.9",
  "Rec": "29",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "32",
  "Player Name": "Brees, Drew",
  "Team": "NO",
  "Position": "QB",
  "Bye": "Wk 6",
  "Yards": "0",
  "TD": "0",
  "INT": "13",
  "YPA": "7.8",
  "Att": "29",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "33",
  "Player Name": "Johnson, Chris",
  "Team": "NYJ",
  "Position": "RB",
  "Bye": "Wk 11",
  "Yards": "255",
  "TD": "2",
  "INT": "0",
  "YPA": "0",
  "Att": "257",
  "Avg": "8",
  "Rec": "32",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "34",
  "Player Name": "Jackson, Vincent",
  "Team": "TB",
  "Position": "WR",
  "Bye": "Wk 7",
  "Yards": "1233",
  "TD": "9",
  "INT": "0",
  "YPA": "0",
  "Att": "2",
  "Avg": "15.4",
  "Rec": "80",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "35",
  "Player Name": "Cruz, Victor",
  "Team": "NYG",
  "Position": "WR",
  "Bye": "Wk 8",
  "Yards": "1301",
  "TD": "8",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "14.3",
  "Rec": "91",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "36",
  "Player Name": "Gerhart, Toby",
  "Team": "JAC",
  "Position": "RB",
  "Bye": "Wk 11",
  "Yards": "277",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "254",
  "Avg": "8.7",
  "Rec": "32",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "37",
  "Player Name": "Thomas, Julius",
  "Team": "DEN",
  "Position": "TE",
  "Bye": "Wk 4",
  "Yards": "844",
  "TD": "10",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.6",
  "Rec": "73",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "38",
  "Player Name": "Brown, Antonio",
  "Team": "PIT",
  "Position": "WR",
  "Bye": "Wk 12",
  "Yards": "1277",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "5",
  "Avg": "13.6",
  "Rec": "94",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "39",
  "Player Name": "Harvin, Percy",
  "Team": "SEA",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "933",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "33",
  "Avg": "13.1",
  "Rec": "71",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "40",
  "Player Name": "Cobb, Randall",
  "Team": "GB",
  "Position": "WR",
  "Bye": "Wk 9",
  "Yards": "1060",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "26",
  "Avg": "12.3",
  "Rec": "86",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "41",
  "Player Name": "Bell, Joique",
  "Team": "DET",
  "Position": "RB",
  "Bye": "Wk 9",
  "Yards": "489",
  "TD": "2",
  "INT": "0",
  "YPA": "0",
  "Att": "177",
  "Avg": "9.6",
  "Rec": "51",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "42",
  "Player Name": "Floyd, Michael",
  "Team": "ARZ",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "1171",
  "TD": "9",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "15.2",
  "Rec": "77",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "43",
  "Player Name": "Bush, Reggie",
  "Team": "DET",
  "Position": "RB",
  "Bye": "Wk 9",
  "Yards": "533",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "158",
  "Avg": "9.7",
  "Rec": "55",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "44",
  "Player Name": "Johnson, Andre",
  "Team": "HOU",
  "Position": "WR",
  "Bye": "Wk 10",
  "Yards": "1211",
  "TD": "8",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "13.8",
  "Rec": "88",
  "Status": "Prob",
  "Injury Type": "Hamstring"
}, {
  "Rank": "45",
  "Player Name": "Patterson, Cordarrelle",
  "Team": "MIN",
  "Position": "WR",
  "Bye": "Wk 10",
  "Yards": "901",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "19",
  "Avg": "14.3",
  "Rec": "63",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "46",
  "Player Name": "Davis, Vernon",
  "Team": "SF",
  "Position": "TE",
  "Bye": "Wk 8",
  "Yards": "828",
  "TD": "9",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "14",
  "Rec": "59",
  "Status": "Prob",
  "Injury Type": "Undisclosed"
}, {
  "Rank": "47",
  "Player Name": "Garcon, Pierre",
  "Team": "WAS",
  "Position": "WR",
  "Bye": "Wk 10",
  "Yards": "1177",
  "TD": "8",
  "INT": "0",
  "YPA": "0",
  "Att": "1",
  "Avg": "13.2",
  "Rec": "89",
  "Status": "Prob",
  "Injury Type": "Hamstring"
}, {
  "Rank": "48",
  "Player Name": "Jennings, Rashad",
  "Team": "NYG",
  "Position": "RB",
  "Bye": "Wk 8",
  "Yards": "288",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "209",
  "Avg": "8",
  "Rec": "36",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "49",
  "Player Name": "Tate, Ben",
  "Team": "CLE",
  "Position": "RB",
  "Bye": "Wk 4",
  "Yards": "233",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "201",
  "Avg": "6.5",
  "Rec": "36",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "50",
  "Player Name": "Foles, Nick",
  "Team": "PHI",
  "Position": "QB",
  "Bye": "Wk 7",
  "Yards": "0",
  "TD": "0",
  "INT": "11",
  "YPA": "7.6",
  "Att": "41",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "51",
  "Player Name": "Cameron, Jordan",
  "Team": "CLE",
  "Position": "TE",
  "Bye": "Wk 4",
  "Yards": "900",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.5",
  "Rec": "78",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "52",
  "Player Name": "Jackson, DeSean",
  "Team": "WAS",
  "Position": "WR",
  "Bye": "Wk 10",
  "Yards": "1121",
  "TD": "8",
  "INT": "0",
  "YPA": "0",
  "Att": "5",
  "Avg": "17",
  "Rec": "66",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "53",
  "Player Name": "Vereen, Shane",
  "Team": "NE",
  "Position": "RB",
  "Bye": "Wk 10",
  "Yards": "755",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "111",
  "Avg": "10.2",
  "Rec": "74",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "54",
  "Player Name": "Luck, Andrew",
  "Team": "IND",
  "Position": "QB",
  "Bye": "Wk 10",
  "Yards": "0",
  "TD": "0",
  "INT": "11",
  "YPA": "7.3",
  "Att": "60",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "55",
  "Player Name": "Richardson, Trent",
  "Team": "IND",
  "Position": "RB",
  "Bye": "Wk 10",
  "Yards": "344",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "180",
  "Avg": "11.5",
  "Rec": "30",
  "Status": "Prob",
  "Injury Type": "Undisclosed"
}, {
  "Rank": "56",
  "Player Name": "Fitzgerald, Larry",
  "Team": "ARZ",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "1050",
  "TD": "9",
  "INT": "0",
  "YPA": "0",
  "Att": "1",
  "Avg": "12.2",
  "Rec": "86",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "57",
  "Player Name": "Hilton, T.Y.",
  "Team": "IND",
  "Position": "WR",
  "Bye": "Wk 10",
  "Yards": "1155",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "4",
  "Avg": "14.4",
  "Rec": "80",
  "Status": "Prob",
  "Injury Type": "Finger"
}, {
  "Rank": "58",
  "Player Name": "Rice, Ray",
  "Team": "BAL",
  "Position": "RB",
  "Bye": "Wk 11",
  "Yards": "344",
  "TD": "2",
  "INT": "0",
  "YPA": "0",
  "Att": "188",
  "Avg": "8.6",
  "Rec": "40",
  "Status": "Out",
  "Injury Type": "Suspension"
}, {
  "Rank": "59",
  "Player Name": "Jones-Drew, Maurice",
  "Team": "OAK",
  "Position": "RB",
  "Bye": "Wk 5",
  "Yards": "288",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "212",
  "Avg": "7.6",
  "Rec": "38",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "60",
  "Player Name": "Crabtree, Michael",
  "Team": "SF",
  "Position": "WR",
  "Bye": "Wk 8",
  "Yards": "1080",
  "TD": "8",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "13.5",
  "Rec": "80",
  "Status": "Prob",
  "Injury Type": "Undisclosed"
}, {
  "Rank": "61",
  "Player Name": "Olsen, Greg",
  "Team": "CAR",
  "Position": "TE",
  "Bye": "Wk 12",
  "Yards": "831",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.5",
  "Rec": "72",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "62",
  "Player Name": "Smith, Torrey",
  "Team": "BAL",
  "Position": "WR",
  "Bye": "Wk 11",
  "Yards": "1133",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "15.3",
  "Rec": "74",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "63",
  "Player Name": "Maclin, Jeremy",
  "Team": "PHI",
  "Position": "WR",
  "Bye": "Wk 7",
  "Yards": "1060",
  "TD": "8",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "14.7",
  "Rec": "72",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "64",
  "Player Name": "Witten, Jason",
  "Team": "DAL",
  "Position": "TE",
  "Bye": "Wk 11",
  "Yards": "877",
  "TD": "6",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.7",
  "Rec": "82",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "65",
  "Player Name": "Ertz, Zach",
  "Team": "PHI",
  "Position": "TE",
  "Bye": "Wk 7",
  "Yards": "811",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "13.1",
  "Rec": "62",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "66",
  "Player Name": "Pitta, Dennis",
  "Team": "BAL",
  "Position": "TE",
  "Bye": "Wk 11",
  "Yards": "844",
  "TD": "6",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.7",
  "Rec": "72",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "67",
  "Player Name": "Ridley, Stevan",
  "Team": "NE",
  "Position": "RB",
  "Bye": "Wk 10",
  "Yards": "77",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "210",
  "Avg": "5.9",
  "Rec": "13",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "68",
  "Player Name": "Gore, Frank",
  "Team": "SF",
  "Position": "RB",
  "Bye": "Wk 8",
  "Yards": "131",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "218",
  "Avg": "8.7",
  "Rec": "15",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "69",
  "Player Name": "Reed, Jordan",
  "Team": "WAS",
  "Position": "TE",
  "Bye": "Wk 10",
  "Yards": "833",
  "TD": "6",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "12.4",
  "Rec": "67",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "70",
  "Player Name": "White, Roddy",
  "Team": "ATL",
  "Position": "WR",
  "Bye": "Wk 9",
  "Yards": "1010",
  "TD": "8",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.5",
  "Rec": "88",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "71",
  "Player Name": "Griffin, Robert",
  "Team": "WAS",
  "Position": "QB",
  "Bye": "Wk 10",
  "Yards": "0",
  "TD": "0",
  "INT": "11",
  "YPA": "7.5",
  "Att": "93",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "72",
  "Player Name": "Brady, Tom",
  "Team": "NE",
  "Position": "QB",
  "Bye": "Wk 10",
  "Yards": "0",
  "TD": "0",
  "INT": "12",
  "YPA": "7.3",
  "Att": "24",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "73",
  "Player Name": "Colston, Marques",
  "Team": "NO",
  "Position": "WR",
  "Bye": "Wk 6",
  "Yards": "990",
  "TD": "8",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "12.5",
  "Rec": "79",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "74",
  "Player Name": "Ryan, Matt",
  "Team": "ATL",
  "Position": "QB",
  "Bye": "Wk 9",
  "Yards": "0",
  "TD": "0",
  "INT": "13",
  "YPA": "7.6",
  "Att": "23",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "75",
  "Player Name": "Stafford, Matthew",
  "Team": "DET",
  "Position": "QB",
  "Bye": "Wk 9",
  "Yards": "0",
  "TD": "0",
  "INT": "16",
  "YPA": "7.4",
  "Att": "32",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "76",
  "Player Name": "Newton, Cam",
  "Team": "CAR",
  "Position": "QB",
  "Bye": "Wk 12",
  "Yards": "0",
  "TD": "0",
  "INT": "12",
  "YPA": "7.5",
  "Att": "104",
  "Avg": "0",
  "Rec": "0",
  "Status": "Prob",
  "Injury Type": "Ankle"
}, {
  "Rank": "77",
  "Player Name": "Welker, Wes",
  "Team": "DEN",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "977",
  "TD": "8",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.7",
  "Rec": "91",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "78",
  "Player Name": "Gordon, Josh",
  "Team": "CLE",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "994",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "4",
  "Avg": "15.3",
  "Rec": "65",
  "Status": "Out",
  "Injury Type": "Suspension"
}, {
  "Rank": "79",
  "Player Name": "Wallace, Mike",
  "Team": "MIA",
  "Position": "WR",
  "Bye": "Wk 5",
  "Yards": "1050",
  "TD": "6",
  "INT": "0",
  "YPA": "0",
  "Att": "5",
  "Avg": "14",
  "Rec": "75",
  "Status": "Prob",
  "Injury Type": "Hamstring"
}, {
  "Rank": "80",
  "Player Name": "Thomas, Pierre",
  "Team": "NO",
  "Position": "RB",
  "Bye": "Wk 6",
  "Yards": "477",
  "TD": "2",
  "INT": "0",
  "YPA": "0",
  "Att": "155",
  "Avg": "8.1",
  "Rec": "59",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "81",
  "Player Name": "Kaepernick, Colin",
  "Team": "SF",
  "Position": "QB",
  "Bye": "Wk 8",
  "Yards": "0",
  "TD": "0",
  "INT": "10",
  "YPA": "7.6",
  "Att": "90",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "82",
  "Player Name": "Williams, Terrance",
  "Team": "DAL",
  "Position": "WR",
  "Bye": "Wk 11",
  "Yards": "946",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "6",
  "Avg": "15.3",
  "Rec": "62",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "83",
  "Player Name": "Watkins, Sammy",
  "Team": "BUF",
  "Position": "WR",
  "Bye": "Wk 9",
  "Yards": "955",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "3",
  "Avg": "17.7",
  "Rec": "54",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "84",
  "Player Name": "Decker, Eric",
  "Team": "NYJ",
  "Position": "WR",
  "Bye": "Wk 11",
  "Yards": "988",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "12",
  "Rec": "82",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "85",
  "Player Name": "Clay, Charles",
  "Team": "MIA",
  "Position": "TE",
  "Bye": "Wk 5",
  "Yards": "723",
  "TD": "6",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.3",
  "Rec": "64",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "86",
  "Player Name": "Miller, Lamar",
  "Team": "MIA",
  "Position": "RB",
  "Bye": "Wk 5",
  "Yards": "188",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "175",
  "Avg": "8.2",
  "Rec": "23",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "87",
  "Player Name": "Bennett, Martellus",
  "Team": "CHI",
  "Position": "TE",
  "Bye": "Wk 9",
  "Yards": "713",
  "TD": "6",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.5",
  "Rec": "62",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "88",
  "Player Name": "Wilson, Russell",
  "Team": "SEA",
  "Position": "QB",
  "Bye": "Wk 4",
  "Yards": "0",
  "TD": "0",
  "INT": "11",
  "YPA": "7.9",
  "Att": "91",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "89",
  "Player Name": "Prater, Matt",
  "Team": "DEN",
  "Position": "K",
  "Bye": "Wk 4",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "90",
  "Player Name": "Rudolph, Kyle",
  "Team": "MIN",
  "Position": "TE",
  "Bye": "Wk 10",
  "Yards": "644",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.5",
  "Rec": "56",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "91",
  "Player Name": "Jackson, Steven",
  "Team": "ATL",
  "Position": "RB",
  "Bye": "Wk 9",
  "Yards": "188",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "187",
  "Avg": "6.7",
  "Rec": "28",
  "Status": "Ques",
  "Injury Type": "Hamstring"
}, {
  "Rank": "92",
  "Player Name": "Green, Ladarius",
  "Team": "SD",
  "Position": "TE",
  "Bye": "Wk 10",
  "Yards": "700",
  "TD": "6",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "12.7",
  "Rec": "55",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "93",
  "Player Name": "Gostkowski, Stephen",
  "Team": "NE",
  "Position": "K",
  "Bye": "Wk 10",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "94",
  "Player Name": "Williams, DeAngelo",
  "Team": "CAR",
  "Position": "RB",
  "Bye": "Wk 12",
  "Yards": "266",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "188",
  "Avg": "11.6",
  "Rec": "23",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "95",
  "Player Name": "Cooper, Riley",
  "Team": "PHI",
  "Position": "WR",
  "Bye": "Wk 7",
  "Yards": "866",
  "TD": "8",
  "INT": "0",
  "YPA": "0",
  "Att": "1",
  "Avg": "15.5",
  "Rec": "56",
  "Status": "Prob",
  "Injury Type": "Foot"
}, {
  "Rank": "96",
  "Player Name": "Sproles, Darren",
  "Team": "PHI",
  "Position": "RB",
  "Bye": "Wk 7",
  "Yards": "599",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "66",
  "Avg": "9.1",
  "Rec": "66",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "97",
  "Player Name": "Evans, Mike",
  "Team": "TB",
  "Position": "WR",
  "Bye": "Wk 7",
  "Yards": "867",
  "TD": "8",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "12.9",
  "Rec": "67",
  "Status": "Prob",
  "Injury Type": "Hamstring"
}, {
  "Rank": "98",
  "Player Name": "Dawson, Phil",
  "Team": "SF",
  "Position": "K",
  "Bye": "Wk 8",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "99",
  "Player Name": "Bowe, Dwayne",
  "Team": "KC",
  "Position": "WR",
  "Bye": "Wk 6",
  "Yards": "866",
  "TD": "8",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "13.1",
  "Rec": "66",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "100",
  "Player Name": "Ingram, Mark",
  "Team": "NO",
  "Position": "RB",
  "Bye": "Wk 6",
  "Yards": "166",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "167",
  "Avg": "9.2",
  "Rec": "18",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "101",
  "Player Name": "Hauschka, Steven",
  "Team": "SEA",
  "Position": "K",
  "Bye": "Wk 4",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "102",
  "Player Name": "Bryant, Matt",
  "Team": "ATL",
  "Position": "K",
  "Bye": "Wk 9",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "103",
  "Player Name": "Tucker, Justin",
  "Team": "BAL",
  "Position": "K",
  "Bye": "Wk 11",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "104",
  "Player Name": "Tate, Golden",
  "Team": "DET",
  "Position": "WR",
  "Bye": "Wk 9",
  "Yards": "933",
  "TD": "6",
  "INT": "0",
  "YPA": "0",
  "Att": "2",
  "Avg": "13.5",
  "Rec": "69",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "105",
  "Player Name": "Stills, Kenny",
  "Team": "NO",
  "Position": "WR",
  "Bye": "Wk 6",
  "Yards": "844",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "5",
  "Avg": "15.3",
  "Rec": "55",
  "Status": "Prob",
  "Injury Type": "Quadriceps"
}, {
  "Rank": "106",
  "Player Name": "Wright, Kendall",
  "Team": "TEN",
  "Position": "WR",
  "Bye": "Wk 9",
  "Yards": "1058",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.8",
  "Rec": "90",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "107",
  "Player Name": "Crosby, Mason",
  "Team": "GB",
  "Position": "K",
  "Bye": "Wk 9",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "108",
  "Player Name": "West, Terrance",
  "Team": "CLE",
  "Position": "RB",
  "Bye": "Wk 4",
  "Yards": "234",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "154",
  "Avg": "9.4",
  "Rec": "25",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "109",
  "Player Name": "Shorts, Cecil",
  "Team": "JAC",
  "Position": "WR",
  "Bye": "Wk 11",
  "Yards": "923",
  "TD": "6",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "12.1",
  "Rec": "76",
  "Status": "Ques",
  "Injury Type": "Hamstring"
}, {
  "Rank": "110",
  "Player Name": "Austin, Tavon",
  "Team": "STL",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "700",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "21",
  "Avg": "12.5",
  "Rec": "56",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "111",
  "Player Name": "Rivers, Philip",
  "Team": "SD",
  "Position": "QB",
  "Bye": "Wk 10",
  "Yards": "0",
  "TD": "0",
  "INT": "12",
  "YPA": "7.9",
  "Att": "27",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "112",
  "Player Name": "Novak, Nick",
  "Team": "SD",
  "Position": "K",
  "Bye": "Wk 10",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "113",
  "Player Name": "Bailey, Dan",
  "Team": "DAL",
  "Position": "K",
  "Bye": "Wk 11",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "114",
  "Player Name": "Randle, Rueben",
  "Team": "NYG",
  "Position": "WR",
  "Bye": "Wk 8",
  "Yards": "855",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "14.3",
  "Rec": "60",
  "Status": "Prob",
  "Injury Type": "Hamstring"
}, {
  "Rank": "115",
  "Player Name": "Miller, Heath",
  "Team": "PIT",
  "Position": "TE",
  "Bye": "Wk 12",
  "Yards": "665",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.7",
  "Rec": "62",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "116",
  "Player Name": "Dobson, Aaron",
  "Team": "NE",
  "Position": "WR",
  "Bye": "Wk 10",
  "Yards": "847",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "14.4",
  "Rec": "59",
  "Status": "Out (PUP-P)",
  "Injury Type": "Foot"
}, {
  "Rank": "117",
  "Player Name": "Gould, Robbie",
  "Team": "CHI",
  "Position": "K",
  "Bye": "Wk 9",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "118",
  "Player Name": "Nicks, Hakeem",
  "Team": "IND",
  "Position": "WR",
  "Bye": "Wk 10",
  "Yards": "845",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "14.8",
  "Rec": "57",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "119",
  "Player Name": "Romo, Tony",
  "Team": "DAL",
  "Position": "QB",
  "Bye": "Wk 11",
  "Yards": "0",
  "TD": "0",
  "INT": "13",
  "YPA": "7.7",
  "Att": "31",
  "Avg": "0",
  "Rec": "0",
  "Status": "Prob",
  "Injury Type": "Back"
}, {
  "Rank": "120",
  "Player Name": "Hopkins, DeAndre",
  "Team": "HOU",
  "Position": "WR",
  "Bye": "Wk 10",
  "Yards": "892",
  "TD": "6",
  "INT": "0",
  "YPA": "0",
  "Att": "2",
  "Avg": "15.1",
  "Rec": "59",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "121",
  "Player Name": "Roethlisberger, Ben",
  "Team": "PIT",
  "Position": "QB",
  "Bye": "Wk 12",
  "Yards": "0",
  "TD": "0",
  "INT": "13",
  "YPA": "7.6",
  "Att": "31",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "122",
  "Player Name": "Henery, Alex",
  "Team": "PHI",
  "Position": "K",
  "Bye": "Wk 7",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "123",
  "Player Name": "Cook, Jared",
  "Team": "STL",
  "Position": "TE",
  "Bye": "Wk 4",
  "Yards": "655",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "12.6",
  "Rec": "52",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "124",
  "Player Name": "Edelman, Julian",
  "Team": "NE",
  "Position": "WR",
  "Bye": "Wk 10",
  "Yards": "934",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "3",
  "Avg": "11.7",
  "Rec": "80",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "125",
  "Player Name": "Cutler, Jay",
  "Team": "CHI",
  "Position": "QB",
  "Bye": "Wk 9",
  "Yards": "0",
  "TD": "0",
  "INT": "15",
  "YPA": "7.5",
  "Att": "34",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "126",
  "Player Name": "Jones, Marvin",
  "Team": "CIN",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "734",
  "TD": "8",
  "INT": "0",
  "YPA": "0",
  "Att": "5",
  "Avg": "13.6",
  "Rec": "54",
  "Status": "Ques",
  "Injury Type": "Ankle"
}, {
  "Rank": "127",
  "Player Name": "Hyde, Carlos",
  "Team": "SF",
  "Position": "RB",
  "Bye": "Wk 8",
  "Yards": "134",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "159",
  "Avg": "6.4",
  "Rec": "21",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "128",
  "Player Name": "Eifert, Tyler",
  "Team": "CIN",
  "Position": "TE",
  "Bye": "Wk 4",
  "Yards": "645",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.9",
  "Rec": "54",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "129",
  "Player Name": "Lee, Marqise",
  "Team": "JAC",
  "Position": "WR",
  "Bye": "Wk 11",
  "Yards": "887",
  "TD": "6",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "13.9",
  "Rec": "64",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "130",
  "Player Name": "Vinatieri, Adam",
  "Team": "IND",
  "Position": "K",
  "Bye": "Wk 10",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "131",
  "Player Name": "Smith, Alex",
  "Team": "KC",
  "Position": "QB",
  "Bye": "Wk 6",
  "Yards": "0",
  "TD": "0",
  "INT": "11",
  "YPA": "7.1",
  "Att": "65",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "132",
  "Player Name": "Benjamin, Kelvin",
  "Team": "CAR",
  "Position": "WR",
  "Bye": "Wk 12",
  "Yards": "826",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "13.5",
  "Rec": "61",
  "Status": "Prob",
  "Injury Type": "Knee"
}, {
  "Rank": "133",
  "Player Name": "Sanders, Emmanuel",
  "Team": "DEN",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "812",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "2",
  "Avg": "13.1",
  "Rec": "62",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "134",
  "Player Name": "Woodhead, Danny",
  "Team": "SD",
  "Position": "RB",
  "Bye": "Wk 10",
  "Yards": "545",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "96",
  "Avg": "8.1",
  "Rec": "67",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "135",
  "Player Name": "Carpenter, Dan",
  "Team": "BUF",
  "Position": "K",
  "Bye": "Wk 9",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "136",
  "Player Name": "McFadden, Darren",
  "Team": "OAK",
  "Position": "RB",
  "Bye": "Wk 5",
  "Yards": "322",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "145",
  "Avg": "10.7",
  "Rec": "30",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "137",
  "Player Name": "Matthews, Jordan",
  "Team": "PHI",
  "Position": "WR",
  "Bye": "Wk 7",
  "Yards": "799",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "12.7",
  "Rec": "63",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "138",
  "Player Name": "Moreno, Knowshon",
  "Team": "MIA",
  "Position": "RB",
  "Bye": "Wk 5",
  "Yards": "207",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "175",
  "Avg": "8",
  "Rec": "26",
  "Status": "Out (PUP-P)",
  "Injury Type": "Knee"
}, {
  "Rank": "139",
  "Player Name": "Ebron, Eric",
  "Team": "DET",
  "Position": "TE",
  "Bye": "Wk 9",
  "Yards": "555",
  "TD": "6",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.5",
  "Rec": "53",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "140",
  "Player Name": "Hunter, Justin",
  "Team": "TEN",
  "Position": "WR",
  "Bye": "Wk 9",
  "Yards": "788",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "14.3",
  "Rec": "55",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "141",
  "Player Name": "Graham, Garrett",
  "Team": "HOU",
  "Position": "TE",
  "Bye": "Wk 10",
  "Yards": "604",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.4",
  "Rec": "58",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "142",
  "Player Name": "Graham, Shayne",
  "Team": "NO",
  "Position": "K",
  "Bye": "Wk 6",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "143",
  "Player Name": "Freeman, Devonta",
  "Team": "ATL",
  "Position": "RB",
  "Bye": "Wk 9",
  "Yards": "233",
  "TD": "2",
  "INT": "0",
  "YPA": "0",
  "Att": "133",
  "Avg": "8.3",
  "Rec": "28",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "144",
  "Player Name": "Boldin, Anquan",
  "Team": "SF",
  "Position": "WR",
  "Bye": "Wk 8",
  "Yards": "833",
  "TD": "6",
  "INT": "0",
  "YPA": "0",
  "Att": "1",
  "Avg": "13",
  "Rec": "64",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "145",
  "Player Name": "Hartline, Brian",
  "Team": "MIA",
  "Position": "WR",
  "Bye": "Wk 5",
  "Yards": "955",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "13.5",
  "Rec": "71",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "146",
  "Player Name": "Amendola, Danny",
  "Team": "NE",
  "Position": "WR",
  "Bye": "Wk 10",
  "Yards": "822",
  "TD": "6",
  "INT": "0",
  "YPA": "0",
  "Att": "2",
  "Avg": "12.5",
  "Rec": "66",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "147",
  "Player Name": "Kearse, Jermaine",
  "Team": "SEA",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "833",
  "TD": "6",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "14.4",
  "Rec": "58",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "148",
  "Player Name": "Stewart, Jonathan",
  "Team": "CAR",
  "Position": "RB",
  "Bye": "Wk 12",
  "Yards": "188",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "188",
  "Avg": "9",
  "Rec": "21",
  "Status": "Prob",
  "Injury Type": "Hamstring"
}, {
  "Rank": "149",
  "Player Name": "Brown, Donald",
  "Team": "SD",
  "Position": "RB",
  "Bye": "Wk 10",
  "Yards": "255",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "112",
  "Avg": "8.8",
  "Rec": "29",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "150",
  "Player Name": "Baldwin, Doug",
  "Team": "SEA",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "866",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "3",
  "Avg": "13.5",
  "Rec": "64",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "151",
  "Player Name": "Feely, Jay",
  "Team": "ARZ",
  "Position": "K",
  "Bye": "Wk 4",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "152",
  "Player Name": "Givens, Chris",
  "Team": "STL",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "799",
  "TD": "6",
  "INT": "0",
  "YPA": "0",
  "Att": "2",
  "Avg": "16.6",
  "Rec": "48",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "153",
  "Player Name": "Allen, Dwayne",
  "Team": "IND",
  "Position": "TE",
  "Bye": "Wk 10",
  "Yards": "566",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.1",
  "Rec": "51",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "154",
  "Player Name": "Bradshaw, Ahmad",
  "Team": "IND",
  "Position": "RB",
  "Bye": "Wk 10",
  "Yards": "154",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "144",
  "Avg": "7.3",
  "Rec": "21",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "155",
  "Player Name": "Walker, Delanie",
  "Team": "TEN",
  "Position": "TE",
  "Bye": "Wk 9",
  "Yards": "551",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10",
  "Rec": "55",
  "Status": "Prob",
  "Injury Type": "Shoulder"
}, {
  "Rank": "156",
  "Player Name": "Boykin, Jarrett",
  "Team": "GB",
  "Position": "WR",
  "Bye": "Wk 9",
  "Yards": "733",
  "TD": "7",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "14.1",
  "Rec": "52",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "157",
  "Player Name": "Britt, Kenny",
  "Team": "STL",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "788",
  "TD": "6",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "14.3",
  "Rec": "55",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "158",
  "Player Name": "Gates, Antonio",
  "Team": "SD",
  "Position": "TE",
  "Bye": "Wk 10",
  "Yards": "545",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.3",
  "Rec": "53",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "159",
  "Player Name": "Chandler, Scott",
  "Team": "BUF",
  "Position": "TE",
  "Bye": "Wk 9",
  "Yards": "544",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.3",
  "Rec": "48",
  "Status": "Ques",
  "Injury Type": "Groin"
}, {
  "Rank": "160",
  "Player Name": "Suisham, Shaun",
  "Team": "PIT",
  "Position": "K",
  "Bye": "Wk 12",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "161",
  "Player Name": "Dalton, Andy",
  "Team": "CIN",
  "Position": "QB",
  "Bye": "Wk 4",
  "Yards": "0",
  "TD": "0",
  "INT": "15",
  "YPA": "7.3",
  "Att": "55",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "162",
  "Player Name": "Pierce, Bernard",
  "Team": "BAL",
  "Position": "RB",
  "Bye": "Wk 11",
  "Yards": "155",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "166",
  "Avg": "6.5",
  "Rec": "24",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "163",
  "Player Name": "Toilolo, Levine",
  "Team": "ATL",
  "Position": "TE",
  "Bye": "Wk 9",
  "Yards": "512",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.9",
  "Rec": "47",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "164",
  "Player Name": "Jennings, Greg",
  "Team": "MIN",
  "Position": "WR",
  "Bye": "Wk 10",
  "Yards": "812",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.8",
  "Rec": "69",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "165",
  "Player Name": "Williams, Mike",
  "Team": "BUF",
  "Position": "WR",
  "Bye": "Wk 9",
  "Yards": "744",
  "TD": "6",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "14.6",
  "Rec": "51",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "166",
  "Player Name": "Succop, Ryan",
  "Team": "KC",
  "Position": "K",
  "Bye": "Wk 6",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "167",
  "Player Name": "Ivory, Chris",
  "Team": "NYJ",
  "Position": "RB",
  "Bye": "Wk 11",
  "Yards": "23",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "157",
  "Avg": "3.8",
  "Rec": "6",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "168",
  "Player Name": "Jones, James",
  "Team": "OAK",
  "Position": "WR",
  "Bye": "Wk 5",
  "Yards": "800",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "12.7",
  "Rec": "63",
  "Status": "Prob",
  "Injury Type": "Hamstring"
}, {
  "Rank": "169",
  "Player Name": "Manuel, EJ",
  "Team": "BUF",
  "Position": "QB",
  "Bye": "Wk 9",
  "Yards": "0",
  "TD": "0",
  "INT": "13",
  "YPA": "6.9",
  "Att": "99",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "170",
  "Player Name": "Cooks, Brandin",
  "Team": "NO",
  "Position": "WR",
  "Bye": "Wk 6",
  "Yards": "788",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "7",
  "Avg": "11.3",
  "Rec": "70",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "171",
  "Player Name": "Fleener, Coby",
  "Team": "IND",
  "Position": "TE",
  "Bye": "Wk 10",
  "Yards": "544",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.9",
  "Rec": "50",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "172",
  "Player Name": "Wheaton, Markus",
  "Team": "PIT",
  "Position": "WR",
  "Bye": "Wk 12",
  "Yards": "775",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "2",
  "Avg": "13.6",
  "Rec": "57",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "173",
  "Player Name": "Lewis, Marcedes",
  "Team": "JAC",
  "Position": "TE",
  "Bye": "Wk 11",
  "Yards": "534",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.9",
  "Rec": "49",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "174",
  "Player Name": "Michael, Christine",
  "Team": "SEA",
  "Position": "RB",
  "Bye": "Wk 4",
  "Yards": "125",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "113",
  "Avg": "7.8",
  "Rec": "16",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "175",
  "Player Name": "Wayne, Reggie",
  "Team": "IND",
  "Position": "WR",
  "Bye": "Wk 10",
  "Yards": "834",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.7",
  "Rec": "71",
  "Status": "Prob",
  "Injury Type": "Knee"
}, {
  "Rank": "176",
  "Player Name": "Manziel, Johnny",
  "Team": "CLE",
  "Position": "QB",
  "Bye": "Wk 4",
  "Yards": "0",
  "TD": "0",
  "INT": "13",
  "YPA": "7.1",
  "Att": "98",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "177",
  "Player Name": "Zuerlein, Greg",
  "Team": "STL",
  "Position": "K",
  "Bye": "Wk 4",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "178",
  "Player Name": "Robinson, Adrien",
  "Team": "NYG",
  "Position": "TE",
  "Bye": "Wk 8",
  "Yards": "523",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.6",
  "Rec": "45",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "179",
  "Player Name": "Celek, Brent",
  "Team": "PHI",
  "Position": "TE",
  "Bye": "Wk 7",
  "Yards": "461",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "12.1",
  "Rec": "38",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "180",
  "Player Name": "Woods, Robert",
  "Team": "BUF",
  "Position": "WR",
  "Bye": "Wk 9",
  "Yards": "744",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "2",
  "Avg": "12",
  "Rec": "62",
  "Status": "Prob",
  "Injury Type": "Ankle"
}, {
  "Rank": "181",
  "Player Name": "Myers, Brandon",
  "Team": "TB",
  "Position": "TE",
  "Bye": "Wk 7",
  "Yards": "501",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.9",
  "Rec": "42",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "182",
  "Player Name": "Gresham, Jermaine",
  "Team": "CIN",
  "Position": "TE",
  "Bye": "Wk 4",
  "Yards": "501",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10",
  "Rec": "50",
  "Status": "Out (PUP-P)",
  "Injury Type": "Hernia"
}, {
  "Rank": "183",
  "Player Name": "Cumberland, Jeff",
  "Team": "NYJ",
  "Position": "TE",
  "Bye": "Wk 11",
  "Yards": "500",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.4",
  "Rec": "44",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "184",
  "Player Name": "Manning, Eli",
  "Team": "NYG",
  "Position": "QB",
  "Bye": "Wk 8",
  "Yards": "0",
  "TD": "0",
  "INT": "16",
  "YPA": "7.6",
  "Att": "23",
  "Avg": "0",
  "Rec": "0",
  "Status": "Prob",
  "Injury Type": "Ankle"
}, {
  "Rank": "185",
  "Player Name": "Housler, Rob",
  "Team": "ARZ",
  "Position": "TE",
  "Bye": "Wk 4",
  "Yards": "499",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.6",
  "Rec": "47",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "186",
  "Player Name": "Washington, Nate",
  "Team": "TEN",
  "Position": "WR",
  "Bye": "Wk 9",
  "Yards": "800",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "15.4",
  "Rec": "52",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "187",
  "Player Name": "Tannehill, Ryan",
  "Team": "MIA",
  "Position": "QB",
  "Bye": "Wk 5",
  "Yards": "0",
  "TD": "0",
  "INT": "14",
  "YPA": "6.9",
  "Att": "36",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "188",
  "Player Name": "Nugent, Mike",
  "Team": "CIN",
  "Position": "K",
  "Bye": "Wk 4",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "189",
  "Player Name": "Quarless, Andrew",
  "Team": "GB",
  "Position": "TE",
  "Bye": "Wk 9",
  "Yards": "488",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.2",
  "Rec": "48",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "190",
  "Player Name": "Kerley, Jeremy",
  "Team": "NYJ",
  "Position": "WR",
  "Bye": "Wk 11",
  "Yards": "766",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "5",
  "Avg": "12.4",
  "Rec": "62",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "191",
  "Player Name": "Miller, Zach",
  "Team": "SEA",
  "Position": "TE",
  "Bye": "Wk 4",
  "Yards": "423",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.8",
  "Rec": "36",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "192",
  "Player Name": "Williams, Andre",
  "Team": "NYG",
  "Position": "RB",
  "Bye": "Wk 8",
  "Yards": "88",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "125",
  "Avg": "6.8",
  "Rec": "13",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "193",
  "Player Name": "Pettigrew, Brandon",
  "Team": "DET",
  "Position": "TE",
  "Bye": "Wk 9",
  "Yards": "477",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.6",
  "Rec": "45",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "194",
  "Player Name": "Daniels, Owen",
  "Team": "BAL",
  "Position": "TE",
  "Bye": "Wk 11",
  "Yards": "477",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.8",
  "Rec": "44",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "195",
  "Player Name": "Wright, Timothy",
  "Team": "TB",
  "Position": "TE",
  "Bye": "Wk 7",
  "Yards": "466",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.8",
  "Rec": "43",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "196",
  "Player Name": "Streater, Rod",
  "Team": "OAK",
  "Position": "WR",
  "Bye": "Wk 5",
  "Yards": "701",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "1",
  "Avg": "14",
  "Rec": "50",
  "Status": "Prob",
  "Injury Type": "Concussion"
}, {
  "Rank": "197",
  "Player Name": "Johnson, Steve",
  "Team": "SF",
  "Position": "WR",
  "Bye": "Wk 8",
  "Yards": "759",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "1",
  "Avg": "13.1",
  "Rec": "58",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "198",
  "Player Name": "Amaro, Jace",
  "Team": "NYJ",
  "Position": "TE",
  "Bye": "Wk 11",
  "Yards": "455",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.1",
  "Rec": "45",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "199",
  "Player Name": "Seferian-Jenkins, Austin",
  "Team": "TB",
  "Position": "TE",
  "Bye": "Wk 7",
  "Yards": "455",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.4",
  "Rec": "40",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "200",
  "Player Name": "Greene, Shonn",
  "Team": "TEN",
  "Position": "RB",
  "Bye": "Wk 9",
  "Yards": "81",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "145",
  "Avg": "6.2",
  "Rec": "13",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "201",
  "Player Name": "Finley, Jermichael",
  "Team": "FA",
  "Position": "TE",
  "Bye": "Wk",
  "Yards": "433",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.4",
  "Rec": "38",
  "Status": "Ques",
  "Injury Type": "Neck"
}, {
  "Rank": "202",
  "Player Name": "Barth, Connor",
  "Team": "TB",
  "Position": "K",
  "Bye": "Wk 7",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "Prob",
  "Injury Type": "Achilles"
}, {
  "Rank": "203",
  "Player Name": "Walsh, Blair",
  "Team": "MIN",
  "Position": "K",
  "Bye": "Wk 10",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "204",
  "Player Name": "Beckham, Odell",
  "Team": "NYG",
  "Position": "WR",
  "Bye": "Wk 8",
  "Yards": "711",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "1",
  "Avg": "16.9",
  "Rec": "42",
  "Status": "Ques",
  "Injury Type": "Hamstring"
}, {
  "Rank": "205",
  "Player Name": "Flacco, Joe",
  "Team": "BAL",
  "Position": "QB",
  "Bye": "Wk 11",
  "Yards": "0",
  "TD": "0",
  "INT": "13",
  "YPA": "7.1",
  "Att": "31",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "206",
  "Player Name": "Carlson, John",
  "Team": "ARZ",
  "Position": "TE",
  "Bye": "Wk 4",
  "Yards": "466",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.6",
  "Rec": "44",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "207",
  "Player Name": "Jackson, Fred",
  "Team": "BUF",
  "Position": "RB",
  "Bye": "Wk 9",
  "Yards": "199",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "112",
  "Avg": "7.4",
  "Rec": "27",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "208",
  "Player Name": "Brown, Andre",
  "Team": "HOU",
  "Position": "RB",
  "Bye": "Wk 10",
  "Yards": "87",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "122",
  "Avg": "5.4",
  "Rec": "16",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "209",
  "Player Name": "Ausberry, David",
  "Team": "OAK",
  "Position": "TE",
  "Bye": "Wk 5",
  "Yards": "455",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.7",
  "Rec": "39",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "210",
  "Player Name": "Freese, Nate",
  "Team": "DET",
  "Position": "K",
  "Bye": "Wk 9",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "211",
  "Player Name": "Gano, Graham",
  "Team": "CAR",
  "Position": "K",
  "Bye": "Wk 12",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "212",
  "Player Name": "LaFell, Brandon",
  "Team": "NE",
  "Position": "WR",
  "Bye": "Wk 10",
  "Yards": "688",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "1",
  "Avg": "13.5",
  "Rec": "51",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "213",
  "Player Name": "Griffin, Ryan",
  "Team": "HOU",
  "Position": "TE",
  "Bye": "Wk 10",
  "Yards": "444",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.4",
  "Rec": "39",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "214",
  "Player Name": "Austin, Miles",
  "Team": "CLE",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "681",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "13.9",
  "Rec": "49",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "215",
  "Player Name": "Roberts, Andre",
  "Team": "WAS",
  "Position": "WR",
  "Bye": "Wk 10",
  "Yards": "677",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.5",
  "Rec": "59",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "216",
  "Player Name": "Moore, Denarius",
  "Team": "OAK",
  "Position": "WR",
  "Bye": "Wk 5",
  "Yards": "676",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "15",
  "Rec": "45",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "217",
  "Player Name": "Smith, Steve",
  "Team": "BAL",
  "Position": "WR",
  "Bye": "Wk 11",
  "Yards": "733",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "12.6",
  "Rec": "58",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "218",
  "Player Name": "Taylor, Stepfan",
  "Team": "ARZ",
  "Position": "RB",
  "Bye": "Wk 4",
  "Yards": "108",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "101",
  "Avg": "7.7",
  "Rec": "14",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "219",
  "Player Name": "Blount, LeGarrette",
  "Team": "PIT",
  "Position": "RB",
  "Bye": "Wk 12",
  "Yards": "23",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "145",
  "Avg": "3.8",
  "Rec": "6",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "220",
  "Player Name": "Brown, Josh",
  "Team": "NYG",
  "Position": "K",
  "Bye": "Wk 8",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "221",
  "Player Name": "Robinson, Khiry",
  "Team": "NO",
  "Position": "RB",
  "Bye": "Wk 6",
  "Yards": "66",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "122",
  "Avg": "8.3",
  "Rec": "8",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "222",
  "Player Name": "Turbin, Robert",
  "Team": "SEA",
  "Position": "RB",
  "Bye": "Wk 4",
  "Yards": "121",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "112",
  "Avg": "8.1",
  "Rec": "15",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "223",
  "Player Name": "Cotchery, Jerricho",
  "Team": "CAR",
  "Position": "WR",
  "Bye": "Wk 12",
  "Yards": "650",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "13.8",
  "Rec": "47",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "224",
  "Player Name": "Fauria, Joseph",
  "Team": "DET",
  "Position": "TE",
  "Bye": "Wk 9",
  "Yards": "402",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.6",
  "Rec": "38",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "225",
  "Player Name": "Latimer, Cody",
  "Team": "DEN",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "579",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "13.5",
  "Rec": "43",
  "Status": "Prob",
  "Injury Type": "Foot"
}, {
  "Rank": "226",
  "Player Name": "Adams, Davante",
  "Team": "GB",
  "Position": "WR",
  "Bye": "Wk 9",
  "Yards": "638",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "14.5",
  "Rec": "44",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "227",
  "Player Name": "Wilson, Marquess",
  "Team": "CHI",
  "Position": "WR",
  "Bye": "Wk 9",
  "Yards": "577",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "12.5",
  "Rec": "46",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "228",
  "Player Name": "Moore, Lance",
  "Team": "PIT",
  "Position": "WR",
  "Bye": "Wk 12",
  "Yards": "577",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "12",
  "Rec": "48",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "229",
  "Player Name": "Janikowski, Sebastian",
  "Team": "OAK",
  "Position": "K",
  "Bye": "Wk 5",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "230",
  "Player Name": "Forbath, Kai",
  "Team": "WAS",
  "Position": "K",
  "Bye": "Wk 10",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "231",
  "Player Name": "Hawkins, Andrew",
  "Team": "CLE",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "666",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "3",
  "Avg": "12.8",
  "Rec": "52",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "232",
  "Player Name": "Hill, Stephen",
  "Team": "NYJ",
  "Position": "WR",
  "Bye": "Wk 11",
  "Yards": "566",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "14.5",
  "Rec": "39",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "233",
  "Player Name": "Brown, Vincent",
  "Team": "SD",
  "Position": "WR",
  "Bye": "Wk 10",
  "Yards": "566",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.8",
  "Rec": "48",
  "Status": "Prob",
  "Injury Type": "Calf"
}, {
  "Rank": "234",
  "Player Name": "Simpson, Jerome",
  "Team": "MIN",
  "Position": "WR",
  "Bye": "Wk 10",
  "Yards": "677",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "15.7",
  "Rec": "43",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "235",
  "Player Name": "Escobar, Gavin",
  "Team": "DAL",
  "Position": "TE",
  "Bye": "Wk 11",
  "Yards": "311",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.7",
  "Rec": "29",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "236",
  "Player Name": "Royal, Eddie",
  "Team": "SD",
  "Position": "WR",
  "Bye": "Wk 10",
  "Yards": "601",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "2",
  "Avg": "13.4",
  "Rec": "45",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "237",
  "Player Name": "Hill, Jeremy",
  "Team": "CIN",
  "Position": "RB",
  "Bye": "Wk 4",
  "Yards": "112",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "113",
  "Avg": "6.2",
  "Rec": "18",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "238",
  "Player Name": "Helu, Roy",
  "Team": "WAS",
  "Position": "RB",
  "Bye": "Wk 10",
  "Yards": "288",
  "TD": "2",
  "INT": "0",
  "YPA": "0",
  "Att": "77",
  "Avg": "7.6",
  "Rec": "38",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "239",
  "Player Name": "Jernigan, Jerrel",
  "Team": "NYG",
  "Position": "WR",
  "Bye": "Wk 8",
  "Yards": "601",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "9",
  "Avg": "12.8",
  "Rec": "47",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "240",
  "Player Name": "Brown, Bryce",
  "Team": "BUF",
  "Position": "RB",
  "Bye": "Wk 9",
  "Yards": "111",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "99",
  "Avg": "8.5",
  "Rec": "13",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "241",
  "Player Name": "Davis, Knile",
  "Team": "KC",
  "Position": "RB",
  "Bye": "Wk 6",
  "Yards": "150",
  "TD": "2",
  "INT": "0",
  "YPA": "0",
  "Att": "71",
  "Avg": "6.5",
  "Rec": "23",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "242",
  "Player Name": "Hillman, Ronnie",
  "Team": "DEN",
  "Position": "RB",
  "Bye": "Wk 4",
  "Yards": "288",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "80",
  "Avg": "8",
  "Rec": "36",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "243",
  "Player Name": "Niklas, Troy",
  "Team": "ARZ",
  "Position": "TE",
  "Bye": "Wk 4",
  "Yards": "355",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.4",
  "Rec": "34",
  "Status": "Ques",
  "Injury Type": "Hand"
}, {
  "Rank": "244",
  "Player Name": "Rodgers, Jacquizz",
  "Team": "ATL",
  "Position": "RB",
  "Bye": "Wk 9",
  "Yards": "323",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "78",
  "Avg": "7.9",
  "Rec": "41",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "245",
  "Player Name": "Floyd, Malcom",
  "Team": "SD",
  "Position": "WR",
  "Bye": "Wk 10",
  "Yards": "655",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "15.2",
  "Rec": "43",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "246",
  "Player Name": "Gibson, Brandon",
  "Team": "MIA",
  "Position": "WR",
  "Bye": "Wk 5",
  "Yards": "655",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.9",
  "Rec": "55",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "247",
  "Player Name": "McCluster, Dexter",
  "Team": "TEN",
  "Position": "WR",
  "Bye": "Wk 9",
  "Yards": "388",
  "TD": "2",
  "INT": "0",
  "YPA": "0",
  "Att": "56",
  "Avg": "8.8",
  "Rec": "44",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "248",
  "Player Name": "Robinson, Allen",
  "Team": "JAC",
  "Position": "WR",
  "Bye": "Wk 11",
  "Yards": "588",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "13.7",
  "Rec": "43",
  "Status": "Ques",
  "Injury Type": "Hamstring"
}, {
  "Rank": "249",
  "Player Name": "Avery, Donnie",
  "Team": "KC",
  "Position": "WR",
  "Bye": "Wk 6",
  "Yards": "643",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "1",
  "Avg": "13.4",
  "Rec": "48",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "250",
  "Player Name": "Kelce, Travis",
  "Team": "KC",
  "Position": "TE",
  "Bye": "Wk 6",
  "Yards": "399",
  "TD": "2",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.7",
  "Rec": "34",
  "Status": "Prob",
  "Injury Type": "Knee"
}, {
  "Rank": "251",
  "Player Name": "Rivera, Mychal",
  "Team": "OAK",
  "Position": "TE",
  "Bye": "Wk 5",
  "Yards": "333",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.7",
  "Rec": "31",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "252",
  "Player Name": "Wilson, David",
  "Team": "NYG",
  "Position": "RB",
  "Bye": "Wk 8",
  "Yards": "177",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "100",
  "Avg": "8.4",
  "Rec": "21",
  "Status": "Ques",
  "Injury Type": "Neck"
}, {
  "Rank": "253",
  "Player Name": "Underwood, Tiquan",
  "Team": "CAR",
  "Position": "WR",
  "Bye": "Wk 12",
  "Yards": "566",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "17.2",
  "Rec": "33",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "254",
  "Player Name": "Burleson, Nate",
  "Team": "CLE",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "566",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "12.9",
  "Rec": "44",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "255",
  "Player Name": "Fasano, Anthony",
  "Team": "KC",
  "Position": "TE",
  "Bye": "Wk 6",
  "Yards": "322",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "9.8",
  "Rec": "33",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "256",
  "Player Name": "Mason, Tre",
  "Team": "STL",
  "Position": "RB",
  "Bye": "Wk 4",
  "Yards": "177",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "101",
  "Avg": "7.1",
  "Rec": "25",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "257",
  "Player Name": "Douglas, Harry",
  "Team": "ATL",
  "Position": "WR",
  "Bye": "Wk 9",
  "Yards": "677",
  "TD": "2",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "13.3",
  "Rec": "51",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "258",
  "Player Name": "Moeaki, Tony",
  "Team": "BUF",
  "Position": "TE",
  "Bye": "Wk 9",
  "Yards": "366",
  "TD": "2",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "9.6",
  "Rec": "38",
  "Status": "Ques",
  "Injury Type": "Hamstring"
}, {
  "Rank": "259",
  "Player Name": "Brown, Marlon",
  "Team": "BAL",
  "Position": "WR",
  "Bye": "Wk 11",
  "Yards": "488",
  "TD": "5",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.8",
  "Rec": "45",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "260",
  "Player Name": "Holmes, Andre",
  "Team": "OAK",
  "Position": "WR",
  "Bye": "Wk 5",
  "Yards": "544",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "15.5",
  "Rec": "35",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "261",
  "Player Name": "Pettis, Austin",
  "Team": "STL",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "600",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "12.2",
  "Rec": "49",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "262",
  "Player Name": "Todman, Jordan",
  "Team": "JAC",
  "Position": "RB",
  "Bye": "Wk 11",
  "Yards": "233",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "100",
  "Avg": "11.1",
  "Rec": "21",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "263",
  "Player Name": "Folk, Nick",
  "Team": "NYJ",
  "Position": "K",
  "Bye": "Wk 11",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "264",
  "Player Name": "Kendricks, Lance",
  "Team": "STL",
  "Position": "TE",
  "Bye": "Wk 4",
  "Yards": "288",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "9.6",
  "Rec": "30",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "265",
  "Player Name": "Sims, Charles",
  "Team": "TB",
  "Position": "RB",
  "Bye": "Wk 7",
  "Yards": "300",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "69",
  "Avg": "8.3",
  "Rec": "36",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "266",
  "Player Name": "Manningham, Mario",
  "Team": "NYG",
  "Position": "WR",
  "Bye": "Wk 8",
  "Yards": "566",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "14.2",
  "Rec": "40",
  "Status": "Prob",
  "Injury Type": "Knee"
}, {
  "Rank": "267",
  "Player Name": "Reece, Marcel",
  "Team": "OAK",
  "Position": "RB",
  "Bye": "Wk 5",
  "Yards": "322",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "58",
  "Avg": "9.5",
  "Rec": "34",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "268",
  "Player Name": "Sturgis, Caleb",
  "Team": "MIA",
  "Position": "K",
  "Bye": "Wk 5",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "269",
  "Player Name": "Ginn, Ted",
  "Team": "ARZ",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "512",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "5",
  "Avg": "15.1",
  "Rec": "34",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "270",
  "Player Name": "Dray, Jim",
  "Team": "CLE",
  "Position": "TE",
  "Bye": "Wk 4",
  "Yards": "301",
  "TD": "2",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.4",
  "Rec": "29",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "271",
  "Player Name": "Jones, Jacoby",
  "Team": "BAL",
  "Position": "WR",
  "Bye": "Wk 11",
  "Yards": "455",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "3",
  "Avg": "12.6",
  "Rec": "36",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "272",
  "Player Name": "Sanu, Mohamed",
  "Team": "CIN",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "512",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "3",
  "Avg": "10.7",
  "Rec": "48",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "273",
  "Player Name": "Starks, James",
  "Team": "GB",
  "Position": "RB",
  "Bye": "Wk 9",
  "Yards": "77",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "100",
  "Avg": "7",
  "Rec": "11",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "274",
  "Player Name": "Toon, Nick",
  "Team": "NO",
  "Position": "WR",
  "Bye": "Wk 6",
  "Yards": "455",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "13",
  "Rec": "35",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "275",
  "Player Name": "Anderson, C.J.",
  "Team": "DEN",
  "Position": "RB",
  "Bye": "Wk 4",
  "Yards": "99",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "80",
  "Avg": "8.3",
  "Rec": "12",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "276",
  "Player Name": "Holmes, Santonio",
  "Team": "FA",
  "Position": "WR",
  "Bye": "Wk",
  "Yards": "566",
  "TD": "2",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "14.2",
  "Rec": "40",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "277",
  "Player Name": "Palmer, Carson",
  "Team": "ARZ",
  "Position": "QB",
  "Bye": "Wk 4",
  "Yards": "0",
  "TD": "0",
  "INT": "19",
  "YPA": "7.4",
  "Att": "31",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "278",
  "Player Name": "Broyles, Ryan",
  "Team": "DET",
  "Position": "WR",
  "Bye": "Wk 9",
  "Yards": "499",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "13.1",
  "Rec": "38",
  "Status": "Prob",
  "Injury Type": "Achilles"
}, {
  "Rank": "279",
  "Player Name": "Paulsen, Logan",
  "Team": "WAS",
  "Position": "TE",
  "Bye": "Wk 10",
  "Yards": "255",
  "TD": "2",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "9.8",
  "Rec": "26",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "280",
  "Player Name": "Cundiff, Billy",
  "Team": "CLE",
  "Position": "K",
  "Bye": "Wk 4",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "281",
  "Player Name": "Avant, Jason",
  "Team": "CAR",
  "Position": "WR",
  "Bye": "Wk 12",
  "Yards": "488",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "12.2",
  "Rec": "40",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "282",
  "Player Name": "Johnson, Charles",
  "Team": "CLE",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "488",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "14.8",
  "Rec": "33",
  "Status": "Prob",
  "Injury Type": "Knee"
}, {
  "Rank": "283",
  "Player Name": "Locker, Jake",
  "Team": "TEN",
  "Position": "QB",
  "Bye": "Wk 9",
  "Yards": "0",
  "TD": "0",
  "INT": "12",
  "YPA": "7.1",
  "Att": "76",
  "Avg": "0",
  "Rec": "0",
  "Status": "Ques",
  "Injury Type": "Foot"
}, {
  "Rank": "284",
  "Player Name": "Dickson, Ed",
  "Team": "CAR",
  "Position": "TE",
  "Bye": "Wk 12",
  "Yards": "301",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10",
  "Rec": "30",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "285",
  "Player Name": "Blackmon, Justin",
  "Team": "JAC",
  "Position": "WR",
  "Bye": "Wk 11",
  "Yards": "455",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "3",
  "Avg": "13.4",
  "Rec": "34",
  "Status": "Out",
  "Injury Type": "Suspension"
}, {
  "Rank": "286",
  "Player Name": "Thompkins, Kenbrell",
  "Team": "NE",
  "Position": "WR",
  "Bye": "Wk 10",
  "Yards": "411",
  "TD": "4",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "12.8",
  "Rec": "32",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "287",
  "Player Name": "Little, Greg",
  "Team": "OAK",
  "Position": "WR",
  "Bye": "Wk 5",
  "Yards": "467",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "13.3",
  "Rec": "35",
  "Status": "Ques",
  "Injury Type": "Hamstring"
}, {
  "Rank": "288",
  "Player Name": "Martin, Keshawn",
  "Team": "HOU",
  "Position": "WR",
  "Bye": "Wk 10",
  "Yards": "455",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "12.6",
  "Rec": "36",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "289",
  "Player Name": "Moncrief, Donte",
  "Team": "IND",
  "Position": "WR",
  "Bye": "Wk 10",
  "Yards": "455",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "13",
  "Rec": "35",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "290",
  "Player Name": "Richardson, Paul",
  "Team": "SEA",
  "Position": "WR",
  "Bye": "Wk 4",
  "Yards": "455",
  "TD": "3",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "13.8",
  "Rec": "33",
  "Status": "Prob",
  "Injury Type": "Shoulder"
}, {
  "Rank": "291",
  "Player Name": "McKinnon, Jerick",
  "Team": "MIN",
  "Position": "RB",
  "Bye": "Wk 10",
  "Yards": "99",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "64",
  "Avg": "7.1",
  "Rec": "14",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "292",
  "Player Name": "Watson, Ben",
  "Team": "NO",
  "Position": "TE",
  "Bye": "Wk 6",
  "Yards": "255",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.6",
  "Rec": "22",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "293",
  "Player Name": "Sudfeld, Zach",
  "Team": "NYJ",
  "Position": "TE",
  "Bye": "Wk 11",
  "Yards": "189",
  "TD": "2",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "9.9",
  "Rec": "19",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "294",
  "Player Name": "Beasley, Cole",
  "Team": "DAL",
  "Position": "WR",
  "Bye": "Wk 11",
  "Yards": "488",
  "TD": "2",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.2",
  "Rec": "48",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "295",
  "Player Name": "Harbor, Clay",
  "Team": "JAC",
  "Position": "TE",
  "Bye": "Wk 11",
  "Yards": "245",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "9.4",
  "Rec": "26",
  "Status": "Ques",
  "Injury Type": "Calf"
}, {
  "Rank": "296",
  "Player Name": "Scobee, Josh",
  "Team": "JAC",
  "Position": "K",
  "Bye": "Wk 11",
  "Yards": "0",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "0",
  "Rec": "0",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "297",
  "Player Name": "McGrath, Sean",
  "Team": "FA",
  "Position": "TE",
  "Bye": "Wk",
  "Yards": "233",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "11.7",
  "Rec": "20",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "298",
  "Player Name": "Winslow, Kellen",
  "Team": "FA",
  "Position": "TE",
  "Bye": "Wk",
  "Yards": "233",
  "TD": "1",
  "INT": "0",
  "YPA": "0",
  "Att": "0",
  "Avg": "10.1",
  "Rec": "23",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "299",
  "Player Name": "Dwyer, Jonathan",
  "Team": "ARZ",
  "Position": "RB",
  "Bye": "Wk 4",
  "Yards": "100",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "89",
  "Avg": "5.9",
  "Rec": "17",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "300",
  "Player Name": "Green-Ellis , BenJarvus",
  "Team": "CIN",
  "Position": "RB",
  "Bye": "Wk 4",
  "Yards": "11",
  "TD": "0",
  "INT": "0",
  "YPA": "0",
  "Att": "87",
  "Avg": "5.5",
  "Rec": "2",
  "Status": "",
  "Injury Type": ""
}, {
  "Rank": "301",
  "Player Name": "Seattle Seahawks",
  "Position": "DEF"
}, {
  "Rank": "302",
  "Player Name": "Carolina Panthers",
  "Position": "DEF"
}, {
  "Rank": "303",
  "Player Name": "San Francisco 49ers",
  "Position": "DEF"
}, {
  "Rank": "304",
  "Player Name": "Denver Broncos",
  "Position": "DEF"
}, {
  "Rank": "305",
  "Player Name": "Arizona Cardinals",
  "Position": "DEF"
}, {
  "Rank": "306",
  "Player Name": "Cincinnati Bengals",
  "Position": "DEF"
}, {
  "Rank": "307",
  "Player Name": "St. Louis Rams",
  "Position": "DEF"
}, {
  "Rank": "308",
  "Player Name": "Kansas City Chiefs",
  "Position": "DEF"
}, {
  "Rank": "309",
  "Player Name": "New England Patriots",
  "Position": "DEF"
}, {
  "Rank": "310",
  "Player Name": "Buffalo Bills",
  "Position": "DEF"
}, {
  "Rank": "311",
  "Player Name": "Tampa Bay Buccaneers",
  "Position": "DEF"
}, {
  "Rank": "312",
  "Player Name": "New Orleans Saints",
  "Position": "DEF"
}, {
  "Rank": "313",
  "Player Name": "Houston Texans",
  "Position": "DEF"
}, {
  "Rank": "314",
  "Player Name": "Baltimore Ravens",
  "Position": "DEF"
}, {
  "Rank": "315",
  "Player Name": "Cleveland Browns",
  "Position": "DEF"
}];
